#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by GradleWrapper
#
##############################################################################

# Attempt to set APP_HOME before any defensiveness
APP_HOME=$( cd "${APP_PATH:-./}." && cd "${APP_NAME%/*}" && pwd -P ) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

# Use the maximum available from the JVM to allocate memory based on the system's capabilities
# This is useful for CI environments where memory is limited
if [ "$CI" ] ; then
    DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS \"-Xmx1g\" \"-Xms256m\""
fi

APP_NAME=gradle
APP_BASE_NAME=${0##*/}
APP_PATH="${APP_PATH:-.}"

# Ensure GRADLE_OPTS is set
: ${GRADLE_OPTS:=""}

# Check if GRADLE_USER_HOME is set, otherwise use default
: ${GRADLE_USER_HOME:="$HOME/.gradle"}

# Prefer the wrapper-specific Gradle distribution
: ${GRADLE_WRAPPER_PATH:="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"}

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation, or install a JDK that contains the Java command."
fi

# Escape application args
save () {
    for i ; do printf '%s\n' "$i" | sed "s/'/'\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}

die () {
    echo "$*"
    exit 1
}

# Collect all arguments for the java command;
#   * if running under Cygwin, interpret the path as Windows path and store in $cygwin_args
#   * if not running under Cygwin, but running on Windows, use CMD.exe to launch
#   * otherwise, use POSIX-style paths
case "$(uname -s)" in
  CYGWIN* )
    # Get constructor arguments
    shift
    # If we're running on Windows, we need to convert the path to Windows format
    if [ "$OSTYPE" = "cygwin" ] ; then
      APP_HOME=$(cygpath --path --mixed "$APP_HOME")
      CLASSPATH=$(cygpath --path --mixed "$APP_HOME/gradle/wrapper/gradle-wrapper.jar")
      JAVACMD=$(cygpath --unix "$JAVACMD")
      
      # We need to run with the Windows version of Java
      if [ -n "$JAVA_HOME" ] ; then
        JAVACMD=$(cygpath --mixed "$JAVACMD")
      fi
    fi
    ;;
  MINGW* )
    # Under MinGw, we need to convert the path to Windows format
    APP_HOME=$(cd "$APP_HOME" && pwd -W)
    CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
    # Remove trailing spaces
    CLASSPATH=$(echo $CLASSPATH | sed 's/[[:space:]]*$//')
    ;;
  * )
    # normal Unix-style path
    CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
    ;;
esac

# If running on Windows, use the .bat file instead
case "$(uname -s)" in
  CYGWIN* | MINGW* | MSYS* )
    # Check if we have a gradlew.bat file
    if [ -f "$APP_HOME/gradlew.bat" ] ; then
      exec cmd //c "$(cygpath --windows "$APP_HOME/gradlew.bat")" "$@"
    fi
    ;;
esac

# Run the Gradle wrapper
exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
